# docs/api/register.yml

openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: ثبت‌نام کاربر و دریافت توکن
      description: >
        این endpoint یک کاربر جدید با فیلدهای نام، ایمیل و پسورد ثبت می‌کند
        و در صورت موفقیت یک توکن JWT برمی‌گرداند.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - password_confirmation
              properties:
                name:
                  type: string
                  maxLength: 255
                  example: masoud
                email:
                  type: string
                  format: email
                  example: masoud@gmail.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: 12345678
                password_confirmation:
                  type: string
                  format: password
                  example: 12345678
      responses:
        '201':
          description: کاربر با موفقیت ثبت شد
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                      token:
                        type: string
                        example: 8|qV2onhpj4iX6j3BQoA8kNyL9n10ZyA0qEiiOt8su585e712c
        '422':
          description: خطای اعتبارسنجی
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
      security: []  # این endpoint عمومی است
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: masoud
        email:
          type: string
          format: email
          example: masoud@gmail.com
        created_at:
          type: string
          format: date-time
          example: '2025-05-10T04:17:31.000000Z'
    ValidationError:
      type: object
      properties:
        message:
          type: string
          example: The email field is required.
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
