# docker-compose.yml

version: '3.8'

services:

    app:
        build: .
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - QUEUE_CONNECTION=redis
            - REDIS_HOST=redis
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:14-alpine
        container_name: laravel_db
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWORD=secret
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
